### PR TITLE
Fix: Location names and cardinal directions in Achievements

### PR DESCRIPTION
**Pull request by eleriaqueen**
In English, location names must be capitalized.
You don't write "in the paris suburbs" but "in the Paris suburbs".

### CODE REVIEW

**Comment by llchrisll** [comment]
Thanks for pointing out these grammatical mistakes, I barely look at this file so I never dealt with the content of it since I took over this project.
If you don't have any more to add, let me know so I can merge it.

**Comment by eleriaqueen** [comment]
I may take a look at the rest of the achievements with capitalization in mind later today or tomorrow. I would say to not merge yet. ^_^

**Comment by eleriaqueen** [comment]
You can merge this one @llchrisll

**Comment by llchrisll** [comment]
Thanks a lot for these fixes :)

**Pull request merged**
