### PR TITLE
Reorganize the Project

### PR DESCRIPTION
**Pull request by llchrisll**
As everyone in my discord will know about this:
I recently made an "pool" about the structure of my project and got kinda "blamed" since it's confusing and holds many unecessary files.

Therefore I tried to come up with a better way of handling and this is it.

I would like to ask you to give me honest feedback about it and if there is something else which I missed, make a comment about it.
So this PR will be merged once everyone is satisfied.

ToDo:
- [ ] Collect feedback
- [ ] Improve based on feedback
- [ ] Recheck everything again

### CODE REVIEW

**Comment by llchrisll** [comment]
Also please note:
If there is no feedback whatsoever in a week, I will merge it.

**Comment by reunite-ro** [comment]
1. All option will print out 2022 client to confirm, so maybe some scripts related there.
2. cls will be created in data\luafiles514\lua files\cls folder when I tried to create for headgear, supposely in \datainfo\ folder.

**Comment by llchrisll** [comment]
Like stated on my discord:
1. fixed already locally, forgot to commit tho as I was on the middle of testing.
2. That's supposed to be there as it's my Custom Lua Support, see my wiki about it

**Comment by llchrisll** [comment]
If there is nothing else anybody wants to add to this PR, I will merge it by the evening (my time) when I get back from work.
Then I will update my new doc site's wiki a bit more about the usage of the Tools, as I only have some basic lines in there.

**Pull request merged**
