### PR TITLE
Implementation of the renamed System folder (SystemEN)

### PR DESCRIPTION
**Pull request by llchrisll**
- also renamed files to a shorter versions
- Adjusted NEMO Profiles/WARP Session files  
  - Removed the following patches from the profiles/sessions:
  > CheckAttendance
  > monster_size_effect
  > PetEvolution
  > PrivateAirplane
- Adjusted .bat files

Feel free test and give feedback about it.
In my opinion it looks better if the translation files are even more split now.
Next commit will be adjusted iteminfo setup so your custom items/overrides have a separate files for them or just custom items, not sure yet.

### CODE REVIEW

**Comment by eleriaqueen** [comment]
Sorry I can't really test this because as a Linux user preparing a client is more involved and annoying because for some reason the batch files don't really work for me under Wine, they don't operate quite right, for instance the one which is about merging files up to a client date doesn't progress after choosing the client date (no idea why, I have almost zero knowledge about .bat files).

I haven't yet reached the point of frustration where I would make my own linux shellscripts to replace the .bat files.

On another note : 
May I ask what motivated the switch to the name `SystemEN` ?
Is it to replace the `_EN` suffix on many files ?

**Comment by reunite-ro** [comment]
questinfo_f.lub still going to old System folder
image

And also typo here the ')'

Table[77].Slot)[2]:AddPerfectEnchant("MT_Soul_RS", 0, {"S_Enchant_Essence", 5} )
Table[77].Slot[2]:AddPerfectEnchant("MT_Soul_PS", 0, {"S_Enchant_Essence", 5} )
Table[77].Slot[2]:AddPerfectEnchant("MT_Soul_EC", 0, {"S_Enchant_Essence", 5} ) 

I dont know if image below related to this PR or not but it seems duplicate/encoding issue
image

**Comment by llchrisll** [comment]
> May I ask what motivated the switch to the name `SystemEN` ? Is it to replace the `_EN` suffix on many files ? Anyway I like the change.

Sorry I overlooked your comment xD.
Basically I wanted to keep the translation files split from korean files, so it's less cluttered.
The new names is just a side effect, as I thought of that afterwards.
I mean there is no real reason to use the _true/sak and ofc the _EN prefix if the files are in their own folder right? :)

**Comment by llchrisll** [comment]
Anyway, I will merge this PR tomorrow if there is no further feedback or even suggestions of improvements :).

**Comment by llchrisll** [comment]
I will merge it locally without the PR to avoid issues, once completed I will close this.

**Comment by Singe-Horizontal** [comment]
Hey chris, there these files are still referencing `monster_size_effect_EN` :
Addons/WARP Sessions/2015_Translation.yml
Addons/WARP Sessions/2018_Translation.yml
Addons/WARP Sessions/2019-06_Translation.yml
Tools/AdditionsGenerator.bat

**Comment by llchrisll** [comment]
> Hey chris, there these files are still referencing `monster_size_effect_EN` : Addons/WARP Sessions/2015_Translation.yml Addons/WARP Sessions/2018_Translation.yml Addons/WARP Sessions/2019-06_Translation.yml Tools/AdditionsGenerator.bat

Yeah I saw that yesterday after recreating a few of my clients as I only tested it with one, made the changes locally already.
Just need some final checks then I can merge

**Pull request merged**
